apiVersion: v1
kind: Service
metadata:
    name: "svsd-e4c3"
    labels:
        app: "svsd-e4c3"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "svsd-e4c3"